[config]
    username = 'username'                     #填入bot的id或是隨意代號
    ip = 'mcfallout.net'
[settings]
    whitelist = ["username1","username2"]     #填入白名單id，若多人需用逗號分隔
    publicity = false                         #是否開啟宣傳
    publicity_content = ["%123","$test"]      #宣傳內容
    interval = 605000                         #每次宣傳的間隔時間，單位為毫秒
    log = true                                #是否將交易內容存至本地( 位置: bot資料夾/logs/日期.txt )
[gamble]
    emerald_range = [0,1000]                  #綠寶石下注範圍 [下限,上限]
    coin_range = [0,10]                       #村民錠下注範圍 [下限,上限]
    odds = [0,2,3,4,7]                        #賠率
    protect_odds = 7                          #破產保護倍數 ( 若 下注金額*破產保護倍數 > 餘額 => 退款 )
    redstone_position = [0,60,0]              #紅石粉座標
    check_position = [[0,59,3],[1,59,4]]      #草地座標 (任一對角)

[discord_setting]
    discord_bot = true                        #是否開啟Discord Bot (使用額外功能務必開啟)
    token = "abc123456789123456789"           #DC Bot的token，詳情請參考#Discord bot Setting   注意! 請勿將此token透漏給不信任的人，否則你的discord bot將有被盜用的風險
    guildID = '123456789123456789'            #DC伺服器的ID，開啟開發者模式後對DC頭像按右鍵即可取得伺服器ID
    bot_status = true                         #狀態頁是否開啟
    bot_status_channel_name = '狀態'          #狀態頁頻道名稱 (可自訂但需與DC群內頻道相符)
    message_log = true                        #訊息頁是否開啟
    only_claim = true                         #僅顯示[系統] [領地] [附近] 訊息
    message_log_channel_name = '訊息'         #訊息頁頻道名稱 (可自訂但需與DC群內頻道相符)
    betting_log = true                        #金流頁是否開啟，內容包括下注輸贏、簽到、領錢
    betting_log_channel_name = '下注狀態'     #金流頁頻道名稱 (可自訂但需與DC群內頻道相符)
    notice_log = true                         #通知頁是否開啟，內容包括轉帳錯誤訊息及DC綁定訊息
    notice_log_channel_name = '通知'          #通知頁頻道名稱 (可自訂但需與DC群內頻道相符)

[custom]                 #自訂義bot
    enable = false
