[dc_role_id]
    ADMIN = '1125665338172907602'
    LINKED = '123456789123456789'   #已驗證身分組id
    auto_give = false
[role]
    daily_role = [  #須按照身分組地位高低，由高到低排列  #[dc身分組名稱,minecraft顯示名字(可自行更換色碼),每日簽到金額]  #"萬"可用大寫"W"代替
        ['測試身分組','&E&L測試身分組','10W'],   #請注意逗號
        ['8787','&B&L我是87','8W']
    ]
[setting]
    default_close = false    #true = 24hr Open
[xlsx]
    enable = true
    custom_data = [true,true,false,false] #[總下注、總獲取、總中獎、總未中獎]